# Generated by Django 4.0.5 on 2022-06-12 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoSeguraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoEquipamentoSeguranca', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do Equipamento de Segurança')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoVeiculo', models.CharField(max_length=200, verbose_name='Descrição do Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=100, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamentoseguranca', models.ManyToManyField(to='core.equipamentoseguraca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
                ('veiculos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculos')),
            ],
        ),
    ]
